# Generated by Django 3.2.9 on 2021-11-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='ipAddress',
            field=models.CharField(max_length=15),
        ),
    ]
