# Generated by Django 3.2.9 on 2021-11-17 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_camera_ipaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='ipAddress',
        ),
    ]
