# Generated by Django 3.2.9 on 2021-11-22 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_camera_ipaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Camera',
        ),
    ]
